import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import SideNavProvider from "./components/SideNavProvider";
import { Toaster } from "@/components/ui/sonner";
import Head from "next/head";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <head>
        <title>Docker Demon</title>
        <link rel="icon" href="/favicon.ico" />
      </head>

      <body className={`antialiased`}>
        <Toaster />
        <SideNavProvider>{children}</SideNavProvider>
      </body>
    </html>
  );
}
